local all u1_bootstrap peer map=u1_os
local all all reject
hostnossl all all all reject
hostssl lunch_bot line_event_app all scram-sha-256
hostssl lunch_bot privacy_app all scram-sha-256
host all all all reject
