listen_addresses = '*'
port = 5432
max_connections = 20
superuser_reserved_connections = 3
shared_buffers = '128MB'
work_mem = '1MB'
maintenance_work_mem = '32MB'
max_parallel_workers_per_gather = 0
max_parallel_workers = 0
max_worker_processes = 0
max_prepared_transactions = 0
max_wal_senders = 0
wal_level = minimal
archive_mode = off
wal_keep_size = 0
max_wal_size = '256MB'
min_wal_size = '80MB'
fsync = on
full_page_writes = on
synchronous_commit = on
timezone = 'UTC'
default_transaction_isolation = 'read committed'
password_encryption = 'scram-sha-256'
ssl = on
ssl_min_protocol_version = 'TLSv1.2'
ssl_cert_file = '/run/u1/server.crt'
ssl_key_file = '/run/u1/server.key'
ssl_ca_file = '/run/u1/ca.crt'
unix_socket_directories = '/run/u1'
unix_socket_permissions = 0700
temp_tablespaces = 'u1_temp'
temp_file_limit = '16MB'
logging_collector = off
log_destination = 'stderr'
log_statement = 'none'
log_duration = off
log_min_duration_statement = -1
log_min_duration_sample = -1
log_transaction_sample_rate = 0
log_min_messages = panic
log_min_error_statement = panic
log_error_verbosity = terse
log_parameter_max_length = 0
log_parameter_max_length_on_error = 0
log_connections = off
log_disconnections = off
log_checkpoints = off
log_autovacuum_min_duration = -1
log_temp_files = -1
shared_preload_libraries = ''
